from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path
from types import ModuleType

ROOT = Path(__file__).resolve().parents[1]


def load_normalizer() -> ModuleType:
    path = ROOT / "tools" / "normalize_rolling_transcript.py"
    spec = importlib.util.spec_from_file_location(
        "normalize_rolling_transcript", path
    )
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def test_adjacent_phrase_triplication_collapses_to_one_copy() -> None:
    normalizer = load_normalizer()
    tokens = "collect a ton of traces collect a ton of traces collect a ton of traces".split()
    output, removed, events = normalizer.collapse_adjacent_exact_repeats(tokens)
    assert output == "collect a ton of traces".split()
    assert removed == 10
    assert len(events) == 1
    assert events[0].block_tokens == 5
    assert events[0].repeat_count == 3


def test_spoken_double_word_is_preserved_but_triple_word_is_collapsed() -> None:
    normalizer = load_normalizer()
    double, removed_double, _ = normalizer.collapse_adjacent_exact_repeats(
        "is is useful".split()
    )
    triple, removed_triple, _ = normalizer.collapse_adjacent_exact_repeats(
        "doing doing doing next".split()
    )
    assert double == "is is useful".split()
    assert removed_double == 0
    assert triple == "doing next".split()
    assert removed_triple == 2


def test_exact_cross_cue_overlap_is_removed_only_when_three_tokens_match() -> None:
    normalizer = load_normalizer()
    assert (
        normalizer.exact_suffix_prefix_overlap(
            "we collect agent trace data".split(),
            "agent trace data then mine it".split(),
        )
        == 3
    )
    assert (
        normalizer.exact_suffix_prefix_overlap(
            "we collect traces".split(),
            "collect traces carefully".split(),
        )
        == 0
    )


def test_normalize_transcript_isolates_transport_footer_and_keeps_raw_authority() -> None:
    normalizer = load_normalizer()
    transcript = {
        "video_id": "CvRngaQZQ3Y",
        "title": "Sample",
        "language": "en",
        "duration_seconds": 20,
        "cues": [
            {
                "start_label": "00:00:00",
                "end_label": "00:00:10",
                "text": "&gt;&gt; collect traces collect traces collect traces",
            },
            {
                "start_label": "00:00:10",
                "end_label": "00:00:20",
                "text": (
                    "collect traces then improve agents --- Generated by "
                    "https://youtube-transcript.ai — service footer"
                ),
            },
        ],
    }
    normalized = normalizer.normalize_transcript(transcript, "0" * 64)
    assert normalized["raw_source_remains_authoritative"] is True
    assert normalized["normalization_status"] == "REVIEW_REQUIRED"
    assert normalized["cues"][0]["normalized_text"] == ">> collect traces"
    assert normalized["cues"][1]["normalized_text"] == "then improve agents"
    assert normalized["metrics"]["removed_transport_footer_characters"] > 0
    assert normalized["transport_footer_findings"][0]["disposition"] == (
        "ISOLATED_AS_TRANSPORT_METADATA"
    )


def test_run_writes_reproducible_derivatives_without_modifying_source(tmp_path: Path) -> None:
    normalizer = load_normalizer()
    source = tmp_path / "transcript.json"
    source_value = {
        "video_id": "CvRngaQZQ3Y",
        "title": "Sample",
        "language": "en",
        "duration_seconds": 10,
        "cues": [
            {
                "start_label": "00:00:00",
                "end_label": "00:00:10",
                "text": "agent trace data agent trace data",
            }
        ],
    }
    source_text = json.dumps(source_value, ensure_ascii=False, sort_keys=True)
    source.write_text(source_text, encoding="utf-8")
    output = tmp_path / "normalized"
    result = normalizer.run(source, output)
    assert source.read_text(encoding="utf-8") == source_text
    assert (output / "normalized-transcript.json").is_file()
    assert (output / "normalized-transcript.txt").is_file()
    assert (output / "normalization-report.json").is_file()
    assert result["metrics"]["raw_subject_word_count"] == 6
    assert result["metrics"]["normalized_word_count"] == 3
