#!/usr/bin/env python3
"""Create an auditable normalized view of a timestamped rolling-caption transcript.

The raw transcript remains authoritative. This tool performs only exact operations:
HTML entity decoding, known transport-footer isolation, adjacent exact-token repeat
collapse, and exact cross-cue suffix/prefix overlap removal. It never corrects words,
proper nouns, punctuation, or meaning.
"""

from __future__ import annotations

import argparse
import hashlib
import html
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Sequence

SCHEMA_VERSION = "rolling-caption-normalization@1"
TOOL_VERSION = "0.1.0"
TRANSPORT_FOOTER_PREFIXES = (
    "--- Generated by https://youtube-transcript.ai",
)


class NormalizationError(RuntimeError):
    """Fail-closed transcript-normalization error."""


@dataclass(frozen=True)
class CollapseEvent:
    token_offset: int
    block_tokens: int
    repeat_count: int


def sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def sha256_file(path: Path) -> str:
    return sha256_bytes(path.read_bytes())


def write_json(path: Path, value: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def isolate_transport_footer(value: str) -> tuple[str, int, str | None]:
    for prefix in TRANSPORT_FOOTER_PREFIXES:
        index = value.find(prefix)
        if index >= 0:
            return value[:index].rstrip(), len(value) - index, prefix
    return value, 0, None


def collapse_adjacent_exact_repeats(
    tokens: Sequence[str], *, maximum_block_tokens: int = 120
) -> tuple[list[str], int, list[CollapseEvent]]:
    """Collapse only provably adjacent exact token blocks.

    Blocks of three or more tokens require two adjacent copies. One- or two-token
    blocks require at least three adjacent copies so normal spoken double words such
    as "is is" remain visible for human review.
    """

    output: list[str] = []
    events: list[CollapseEvent] = []
    removed = 0
    index = 0
    total = len(tokens)
    while index < total:
        selected: tuple[int, int] | None = None
        maximum = min(maximum_block_tokens, (total - index) // 2)
        for block_size in range(maximum, 0, -1):
            block = list(tokens[index : index + block_size])
            repeat_count = 1
            while (
                index + (repeat_count + 1) * block_size <= total
                and list(
                    tokens[
                        index + repeat_count * block_size :
                        index + (repeat_count + 1) * block_size
                    ]
                )
                == block
            ):
                repeat_count += 1
            required = 3 if block_size < 3 else 2
            if repeat_count >= required:
                selected = (block_size, repeat_count)
                break
        if selected is None:
            output.append(tokens[index])
            index += 1
            continue
        block_size, repeat_count = selected
        output.extend(tokens[index : index + block_size])
        removed += block_size * (repeat_count - 1)
        events.append(
            CollapseEvent(
                token_offset=index,
                block_tokens=block_size,
                repeat_count=repeat_count,
            )
        )
        index += block_size * repeat_count
    return output, removed, events


def exact_suffix_prefix_overlap(
    previous: Sequence[str],
    current: Sequence[str],
    *,
    minimum_tokens: int = 3,
    maximum_tokens: int = 180,
) -> int:
    maximum = min(len(previous), len(current), maximum_tokens)
    for size in range(maximum, minimum_tokens - 1, -1):
        if list(previous[-size:]) == list(current[:size]):
            return size
    return 0


def normalize_transcript(value: dict[str, Any], source_sha256: str) -> dict[str, Any]:
    cues = value.get("cues")
    if not isinstance(cues, list) or not cues:
        raise NormalizationError("transcript JSON must contain a non-empty cues array")

    accumulated: list[str] = []
    normalized_cues: list[dict[str, Any]] = []
    raw_word_count = 0
    removed_adjacent = 0
    removed_overlap = 0
    removed_footer_characters = 0
    collapse_events = 0
    footer_findings: list[dict[str, str]] = []

    for cue_index, cue in enumerate(cues):
        if not isinstance(cue, dict):
            raise NormalizationError(f"cue {cue_index} is not an object")
        raw_text = cue.get("text")
        start_label = cue.get("start_label")
        end_label = cue.get("end_label")
        if not isinstance(raw_text, str) or not isinstance(start_label, str):
            raise NormalizationError(
                f"cue {cue_index} requires string text and start_label"
            )
        decoded = html.unescape(raw_text).replace("\u200b", " ").strip()
        subject_text, footer_characters, footer_prefix = isolate_transport_footer(
            decoded
        )
        if footer_prefix:
            footer_findings.append(
                {
                    "cue_start": start_label,
                    "prefix": footer_prefix,
                    "disposition": "ISOLATED_AS_TRANSPORT_METADATA",
                }
            )
        removed_footer_characters += footer_characters
        raw_tokens = subject_text.split()
        raw_word_count += len(raw_tokens)
        collapsed, adjacent_removed, events = collapse_adjacent_exact_repeats(
            raw_tokens
        )
        overlap = exact_suffix_prefix_overlap(accumulated, collapsed)
        visible_tokens = collapsed[overlap:]
        accumulated.extend(visible_tokens)
        removed_adjacent += adjacent_removed
        removed_overlap += overlap
        collapse_events += len(events)
        normalized_text = " ".join(visible_tokens)
        if normalized_text:
            normalized_cues.append(
                {
                    "start_label": start_label,
                    "end_label": end_label,
                    "normalized_text": normalized_text,
                    "raw_subject_word_count": len(raw_tokens),
                    "normalized_word_count": len(visible_tokens),
                    "removed_adjacent_duplicate_tokens": adjacent_removed,
                    "removed_cross_cue_overlap_tokens": overlap,
                    "collapse_event_count": len(events),
                }
            )

    if not normalized_cues or not accumulated:
        raise NormalizationError("normalization produced no subject-matter text")

    return {
        "schema_version": SCHEMA_VERSION,
        "tool": {
            "name": "normalize_rolling_transcript.py",
            "version": TOOL_VERSION,
        },
        "video_id": value.get("video_id"),
        "title": value.get("title"),
        "language": value.get("language"),
        "duration_seconds": value.get("duration_seconds"),
        "source_transcript_sha256": source_sha256,
        "normalization_status": "REVIEW_REQUIRED",
        "raw_source_remains_authoritative": True,
        "rules": [
            "HTML entities decoded; no lexical substitution",
            "known transport footer isolated from subject-matter cues",
            "exact adjacent token blocks of length >=3 collapsed when repeated >=2 times",
            "exact adjacent token blocks of length 1-2 collapsed only when repeated >=3 times",
            "exact cross-cue suffix-prefix overlap of >=3 tokens removed",
            "no proper-noun, punctuation, grammar, or semantic correction",
        ],
        "metrics": {
            "input_cue_count": len(cues),
            "output_cue_count": len(normalized_cues),
            "raw_subject_word_count": raw_word_count,
            "normalized_word_count": len(accumulated),
            "removed_adjacent_duplicate_tokens": removed_adjacent,
            "removed_cross_cue_overlap_tokens": removed_overlap,
            "removed_transport_footer_characters": removed_footer_characters,
            "collapse_event_count": collapse_events,
        },
        "transport_footer_findings": footer_findings,
        "cues": normalized_cues,
    }


def render_text(value: dict[str, Any]) -> str:
    lines = []
    for cue in value["cues"]:
        end = cue.get("end_label") or "LOCATOR_MISSING"
        lines.append(
            f"[{cue['start_label']} --> {end}] {cue['normalized_text']}"
        )
    return "\n".join(lines) + "\n"


def build_report(value: dict[str, Any], normalized_text_sha256: str) -> dict[str, Any]:
    return {
        "schema_version": "rolling-caption-normalization-report@1",
        "video_id": value.get("video_id"),
        "source_transcript_sha256": value["source_transcript_sha256"],
        "normalized_transcript_sha256": normalized_text_sha256,
        "normalization_status": value["normalization_status"],
        "raw_source_remains_authoritative": True,
        "rules": value["rules"],
        "metrics": value["metrics"],
        "transport_footer_findings": value["transport_footer_findings"],
    }


def run(transcript_path: Path, output_dir: Path) -> dict[str, Any]:
    if not transcript_path.is_file():
        raise NormalizationError(f"transcript does not exist: {transcript_path}")
    output_dir.mkdir(parents=True, exist_ok=True)
    if any(output_dir.iterdir()):
        raise NormalizationError("output directory must be empty")
    source_bytes = transcript_path.read_bytes()
    source = json.loads(source_bytes.decode("utf-8"))
    if not isinstance(source, dict):
        raise NormalizationError("transcript JSON root must be an object")
    normalized = normalize_transcript(source, sha256_bytes(source_bytes))
    normalized_text = render_text(normalized)
    normalized_text_sha = sha256_bytes(normalized_text.encode("utf-8"))

    json_path = output_dir / "normalized-transcript.json"
    text_path = output_dir / "normalized-transcript.txt"
    report_path = output_dir / "normalization-report.json"
    write_json(json_path, normalized)
    text_path.write_text(normalized_text, encoding="utf-8")
    report = build_report(normalized, normalized_text_sha)
    write_json(report_path, report)
    return {
        "normalized_transcript_json": {
            "path": json_path.as_posix(),
            "sha256": sha256_file(json_path),
        },
        "normalized_transcript_text": {
            "path": text_path.as_posix(),
            "sha256": sha256_file(text_path),
        },
        "normalization_report": {
            "path": report_path.as_posix(),
            "sha256": sha256_file(report_path),
        },
        "metrics": report["metrics"],
    }


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--transcript", required=True, type=Path)
    parser.add_argument("--output-dir", required=True, type=Path)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    result = run(args.transcript.resolve(), args.output_dir.resolve())
    print(json.dumps(result, ensure_ascii=False, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
